!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - buffer_size
    - 30000
  - - ent_coef
    - auto_0.1
  - - gamma
    - 0.99
  - - gradient_steps
    - 600
  - - learning_rate
    - 0.0003
  - - learning_starts
    - 0
  - - n_timesteps
    - 5000.0
  - - policy
    - CustomSACPolicy
  - - train_freq
    - 3000
  - - vae_path
    - ./vae/chk/vae-level-1-dim-64.pkl
  - - z_size
    - 64
  - - MIN_THROTTLE
    - 0.4
  - - MAX_THROTTLE
    - 0.5
  - - FRAME_SKIP
    - 1
  - - MAX_CTE_ERROR
    - 1.6
  - - N_COMMAND_HISTORY
    - 20
  - - MAX_STEERING_DIFF
    - 0.15
